# Generated by Django 5.2.8 on 2025-12-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rappiSafe', '0002_repartidorprofile_nombre_aseguradora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidorprofile',
            name='agitacion_habilitada',
            field=models.BooleanField(default=True, verbose_name='Detección de agitación habilitada'),
        ),
        migrations.AddField(
            model_name='repartidorprofile',
            name='sensibilidad_agitacion',
            field=models.IntegerField(default=15, verbose_name='Sensibilidad de agitación (10-30)'),
        ),
    ]
