# Generated by Django 5.2.8 on 2025-12-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rappiSafe', '0003_repartidorprofile_agitacion_habilitada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('llamada', 'Llamada')], default='sms', max_length=20, verbose_name='Método de notificación')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('mensaje', models.TextField(verbose_name='Mensaje enviado')),
                ('respuesta_api', models.JSONField(blank=True, null=True, verbose_name='Respuesta del servicio')),
                ('enviado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_contactos', to='rappiSafe.alerta')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='rappiSafe.contactoconfianza')),
            ],
            options={
                'verbose_name': 'Notificación a Contacto',
                'verbose_name_plural': 'Notificaciones a Contactos',
                'ordering': ['-enviado_en'],
            },
        ),
    ]
