# Generated by Django 5.2.8 on 2025-12-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rappiSafe', '0004_notificacioncontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoconfianza',
            name='email',
            field=models.EmailField(blank=True, help_text='Email para recibir alertas', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactoconfianza',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Obtenlo hablando con @userinfobot en Telegram', max_length=50, verbose_name='ID de Telegram'),
        ),
    ]
