# Generated by Django 5.2.8 on 2025-12-10 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rappiSafe', '0005_contactoconfianza_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número telefónico debe contener entre 10 y 20 dígitos.', regex='^\\+?[\\d\\s\\-\\(\\)]{10,20}$')], verbose_name='Teléfono'),
        ),
    ]
