# Generated by Django 5.2.8 on 2025-12-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rappiSafe', '0006_alter_user_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactoconfianza',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactoconfianza',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='estadisticariesgo',
            name='puntuacion_riesgo',
            field=models.FloatField(verbose_name='Puntuación de riesgo (1-10)'),
        ),
    ]
